# Generated by Django 5.2.6 on 2025-09-24 23:10
from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "published": "A post available for all to view",
        "Well off": "A post only visible to the author"
    }
        
    Status = apps.get_model("Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_status'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
