# Generated by Django 5.2.6 on 2025-09-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20250924_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='desription',
            new_name='description',
        ),
    ]
