# Generated by Django 5.2.6 on 2025-09-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_desription_status_description'),
    ]

    operations = [
    ]
